In [7]:
import pandas as pd
url = 'http://winterolympicsmedals.com/medals.csv'
data = pd.read_csv(url)
data.head(30)

,Year,City,Sport,Discipline,NOC,Event,Event gender,Medal
0,1924,Chamonix,Skating,Figure skating,AUT,individual,M,Silver
1,1924,Chamonix,Skating,Figure skating,AUT,individual,W,Gold
2,1924,Chamonix,Skating,Figure skating,AUT,pairs,X,Gold
3,1924,Chamonix,Bobsleigh,Bobsleigh,BEL,four-man,M,Bronze
4,1924,Chamonix,Ice Hockey,Ice Hockey,CAN,ice hockey,M,Gold
5,1924,Chamonix,Biathlon,Biathlon,FIN,military patrol,M,Silver
6,1924,Chamonix,Skating,Figure skating,FIN,pairs,X,Silver
7,1924,Chamonix,Skating,Speed skating,FIN,10000m,M,Gold
8,1924,Chamonix,Skating,Speed skating,FIN,10000m,M,Silver
9,1924,Chamonix,Skating,Speed skating,FIN,1500m,M,Gold
10,1924,Chamonix,Skating,Speed skating,FIN,5000m,M,Gold
11,1924,Chamonix,Skating,Speed skating,FIN,5000m,M,Silver
12,1924,Chamonix,Skating,Speed skating,FIN,500m,M,Bronze
13,1924,Chamonix,Skating,Speed skating,FIN,combined (4 events),M,Bronze
14,1924,Chamonix,Skating,Speed skating,FIN,combined (4 events),M,Gold
15,1924,Chamonix,Skiing,Cross Country S,FIN,18km,M,Bronze
16,1924,Chamonix,Biathlon,Biathlon,FRA,military patrol,M,Bronze
17,1924,Chamonix,Curling,Curling,FRA,curling,M,Bronze
18,1924,Chamonix,Skating,Figure skating,FRA,pairs,X,Bronze
19,1924,Chamonix,Bobsleigh,Bobsleigh,GBR,four-man,M,Silver
20,1924,Chamonix,Curling,Curling,GBR,curling,M,Gold
21,1924,Chamonix,Ice Hockey,Ice Hockey,GBR,ice hockey,M,Bronze
22,1924,Chamonix,Skating,Figure skating,GBR,individual,W,Bronze
23,1924,Chamonix,Skating,Speed skating,NOR,10000m,M,Bronze
24,1924,Chamonix,Skating,Speed skating,NOR,1500m,M,Bronze
25,1924,Chamonix,Skating,Speed skating,NOR,1500m,M,Silver
26,1924,Chamonix,Skating,Speed skating,NOR,5000m,M,Bronze
27,1924,Chamonix,Skating,Speed skating,NOR,500m,M,Bronze
28,1924,Chamonix,Skating,Speed skating,NOR,500m,M,Silver
29,1924,Chamonix,Skating,Speed skating,NOR,combined (4 events),M,Silver

In [ ]:
#C√°c nƒÉm t·ªï ch·ª©c th·∫ø v·∫≠n h·ªôi 
data['Year'].unique()

array([1924, 1928, 1932, 1936, 1948, 1952, 1956, 1960, 1964, 1968, 1972,
       1976, 1980, 1984, 1988, 1992, 1994, 1998, 2002, 2006])

In [ ]:
#C√°c th√†nh ph·ªë t·ªï ch·ª©c 
data['City'].unique()

array(['Chamonix', 'St. Moritz', 'Lake Placid', 'Garmisch-Partenkirchen',
       'Oslo', "Cortina d'Ampezzo", 'Squaw Valley', 'Innsbruck',
       'Grenoble', 'Sapporo', 'Sarajevo', 'Calgary', 'Albertville',
       'Lillehammer', 'Nagano', 'Salt Lake City', 'Turin'], dtype=object)

In [ ]:
#C√°c m√¥n th·ªÉ thaothao
data['Sport'].unique()

array(['Skating', 'Bobsleigh', 'Ice Hockey', 'Biathlon', 'Skiing',
       'Curling', 'Luge'], dtype=object)

In [ ]:
#c√°c h√¨nh th·ª©c thi ƒë·∫•u
data['Discipline'].unique()

array(['Figure skating', 'Bobsleigh', 'Ice Hockey', 'Biathlon',
       'Speed skating', 'Cross Country S', 'Curling', 'Nordic Combined',
       'Ski Jumping', 'Skeleton', 'Alpine Skiing', 'Luge',
       'Short Track S.', 'Freestyle Ski.', 'Snowboard'], dtype=object)

In [ ]:
#T·ªïng c√°c huy ch∆∞∆°ng ƒë∆∞·ª£c trao t·ª´ 1924 ƒë·∫øn 2006 
data['Medal'].value_counts()

Gold      774
Silver    773
Bronze    764
Name: Medal, dtype: int64

In [ ]:
#gi·ªõi t√≠nh tham gia 
data['Event gender'].value_counts()

M    1386
W     802
X     123
Name: Event gender, dtype: int64

In [ ]:
data['Event'].unique()

array(['individual', 'pairs', 'four-man', 'ice hockey', 'military patrol',
       '10000m', '1500m', '5000m', '500m', 'combined (4 events)', '18km',
       'curling', '50km', 'K90 individual (70m)', 'five-man', 'two-man',
       '4x10km relay', 'alpine combined', 'downhill', 'slalom',
       'giant slalom', '10km', '30km mass start', '3x5km relay', '15km',
       '1000m', '20km', '3000m', 'doubles', 'singles', '5km',
       'K120 individual (90m)', '4x7.5km relay', '4x5km relay',
       'ice dancing', 'super-G', 'Team', 'K120 team (90m)', '3000m relay',
       '5000m relay', '3x7.5km relay', '7.5km', '15km mass start', '30km',
       'Combined 5km + 10km pursuit', 'moguls', '10km pursuit',
       'Combined 10km + 15km pursuit', 'aerials', 'giant-slalom',
       'Half-pipe', 'sprint', '5km pursuit', '12.5km pursuit',
       'Giant parallel slalom', 'Sprint 1.5km', 'sprint 1.5km',
       'Alpine combined', 'Individual', 'Individual sprint',
       'Team pursuit', 'Team sprint', 'Snowboard Cross',
       'Combined 7.5 + 7.5km mass start', '4x6km relay',
       '12.5km mass start', 'Combined 15 + 15km mass start'], dtype=object)

In [ ]:
#L·ªçc s·ªë huy ch∆∞∆°ng v√†ng 
data[data['Medal']=='Gold']

,Year,City,Sport,Discipline,NOC,Event,Event gender,Medal
1,1924,Chamonix,Skating,Figure skating,AUT,individual,W,Gold
2,1924,Chamonix,Skating,Figure skating,AUT,pairs,X,Gold
4,1924,Chamonix,Ice Hockey,Ice Hockey,CAN,ice hockey,M,Gold
7,1924,Chamonix,Skating,Speed skating,FIN,10000m,M,Gold
9,1924,Chamonix,Skating,Speed skating,FIN,1500m,M,Gold
...,...,...,...,...,...,...,...,...
2301,2006,Turin,Skiing,Alpine Skiing,USA,Alpine combined,M,Gold
2302,2006,Turin,Skiing,Alpine Skiing,USA,giant slalom,W,Gold
2305,2006,Turin,Skiing,Snowboard,USA,Half-pipe,M,Gold
2307,2006,Turin,Skiing,Snowboard,USA,Half-pipe,W,Gold
2309,2006,Turin,Skiing,Snowboard,USA,Snowboard Cross,M,Gold

In [ ]:
#L·ªçc s·ªë huy ch∆∞∆°ng b·∫°cb·∫°c 
data[data['Medal']=='Silver']

,Year,City,Sport,Discipline,NOC,Event,Event gender,Medal
0,1924,Chamonix,Skating,Figure skating,AUT,individual,M,Silver
5,1924,Chamonix,Biathlon,Biathlon,FIN,military patrol,M,Silver
6,1924,Chamonix,Skating,Figure skating,FIN,pairs,X,Silver
8,1924,Chamonix,Skating,Speed skating,FIN,10000m,M,Silver
11,1924,Chamonix,Skating,Speed skating,FIN,5000m,M,Silver
...,...,...,...,...,...,...,...,...
2296,2006,Turin,Skating,Speed skating,USA,1000m,M,Silver
2298,2006,Turin,Skating,Speed skating,USA,1500m,M,Silver
2306,2006,Turin,Skiing,Snowboard,USA,Half-pipe,M,Silver
2308,2006,Turin,Skiing,Snowboard,USA,Half-pipe,W,Silver
2310,2006,Turin,Skiing,Snowboard,USA,Snowboard Cross,W,Silver

In [ ]:
#L·ªçc s·ªë huy ch∆∞∆°ng ƒë·ªìng
data[data['Medal']=='Bronze']

,Year,City,Sport,Discipline,NOC,Event,Event gender,Medal
3,1924,Chamonix,Bobsleigh,Bobsleigh,BEL,four-man,M,Bronze
12,1924,Chamonix,Skating,Speed skating,FIN,500m,M,Bronze
13,1924,Chamonix,Skating,Speed skating,FIN,combined (4 events),M,Bronze
15,1924,Chamonix,Skiing,Cross Country S,FIN,18km,M,Bronze
16,1924,Chamonix,Biathlon,Biathlon,FRA,military patrol,M,Bronze
...,...,...,...,...,...,...,...,...
2291,2006,Turin,Skating,Short Track S.,USA,1000m,M,Bronze
2292,2006,Turin,Skating,Short Track S.,USA,5000m relay,M,Bronze
2297,2006,Turin,Skating,Speed skating,USA,1500m,M,Bronze
2303,2006,Turin,Skiing,Freestyle Ski.,USA,moguls,M,Bronze
2304,2006,Turin,Skiing,Snowboard,USA,Giant parallel slalom,W,Bronze

In [ ]:
#C√°c huy ch∆∞∆°ng ƒë√£ ƒë∆∞·ª£c trao 
data['Year'].value_counts()

2006    252
2002    234
1998    205
1994    183
1992    171
1988    138
1984    117
1980    115
1976    111
1968    106
1972    105
1964    103
1960     81
1956     72
1948     68
1952     67
1936     51
1924     49
1932     42
1928     41
Name: Year, dtype: int64

In [ ]:
#T·ªïng s·ªë huy ch∆∞∆°ng c·ªßa c√°c n∆∞·ªõc tham gia 
data['NOC'].value_counts()

NOR    280
USA    216
URS    194
AUT    185
GER    158
FIN    151
CAN    119
SUI    118
SWE    118
GDR    110
ITA    101
FRA     83
NED     78
RUS     76
FRG     41
CHN     33
JPN     32
KOR     31
TCH     25
EUN     23
GBR     21
EUA     19
CZE     10
LIE      9
POL      8
CRO      7
BUL      6
EST      6
AUS      6
BLR      6
HUN      6
UKR      5
BEL      5
KAZ      5
YUG      4
SLO      4
ESP      2
PRK      2
LUX      2
LAT      1
ROU      1
DEN      1
UZB      1
NZL      1
SVK      1
Name: NOC, dtype: int64

In [4]:
#L·ªçc v·ªÅ c√°c huy ch∆∞∆°ng c·ªßa n∆∞·ªõc ƒê·ª©c 
F = data.set_index(data['NOC'])
F.loc['GER']

,Year,City,Sport,Discipline,NOC,Event,Event gender,Medal
NOC,,,,,,,,
GER,1928,St. Moritz,Bobsleigh,Bobsleigh,GER,five-man,M,Bronze
GER,1932,Lake Placid,Bobsleigh,Bobsleigh,GER,four-man,M,Bronze
GER,1932,Lake Placid,Ice Hockey,Ice Hockey,GER,ice hockey,M,Bronze
GER,1936,Garmisch-Partenkirchen,Skating,Figure skating,GER,individual,M,Silver
GER,1936,Garmisch-Partenkirchen,Skating,Figure skating,GER,pairs,X,Gold
...,...,...,...,...,...,...,...,...
GER,2006,Turin,Skiing,Cross Country S,GER,sprint 1.5km,W,Silver
GER,2006,Turin,Skiing,Nordic Combined,GER,Individual,M,Gold
GER,2006,Turin,Skiing,Nordic Combined,GER,Individual sprint,M,Bronze
GER,2006,Turin,Skiing,Nordic Combined,GER,Team,M,Silver
GER,2006,Turin,Skiing,Snowboard,GER,Giant parallel slalom,W,Silver

In [6]:
#S·ªë huy ch∆∞∆°ng c·ªßa HungHungary qua c√°c m√πa th·∫ø v·∫≠n h·ªôi 
H = data.set_index(data['NOC'])
H.loc['HUN']

,Year,City,Sport,Discipline,NOC,Event,Event gender,Medal
NOC,,,,,,,,
HUN,1932,Lake Placid,Skating,Figure skating,HUN,pairs,X,Bronze
HUN,1936,Garmisch-Partenkirchen,Skating,Figure skating,HUN,pairs,X,Bronze
HUN,1948,St. Moritz,Skating,Figure skating,HUN,pairs,X,Silver
HUN,1952,Oslo,Skating,Figure skating,HUN,pairs,X,Bronze
HUN,1956,Cortina d'Ampezzo,Skating,Figure skating,HUN,pairs,X,Bronze
HUN,1980,Lake Placid,Skating,Figure skating,HUN,ice dancing,X,Silver